### ISSUE TITLE
Asset upload ignores certain form-data parameters 

### ISSUE THREAD

**Issue by InuKami16** [contentstack/contentstack-management-java#45]
#32 Has not been fixed. The `uploadAsset(String filePath, String parentUid, String title, String description, String[] tags)` method effectively ignores `parentUid, title, tags` arguments. When calling this method with `parentUid, title, tags`, the asset will not be uploaded under the folder with with uid `parentUid`, the title of the asset will be the file name instead of the given `title`, and the tags on the asset will be empty. When looking at the code in the `Asset` class, the `asset[parentUid], asset[title], asset[tags]` form-data are added, but they are effectively ignored since you only use the part at index 0, which is the `asset[upload]`. To fix this, you should add the form-data parameters, `asset[parentUid], asset[title], asset[tags]`, to the body instead where the `asset[description]` is and refactor your `AssetService` class.

**Comment by ishaileshmishra** [comment]
Thank you, @InuKami16, for highlighting this issue. We appreciate your input. We will carefully review the solution you've proposed to address the matter and keep you informed once the fix is available.

**Comment by reeshika-h** [comment]
Hey @InuKami16, Kindly checkout the latest version 1.4.3. Let us know if you face the same issue.
